// SPDX-License-Identifier: MIT
// Copyright (c) 2025. Csaba Dudas (CsabaDu)

namespace CsabaDu.DynamicTestData.DynamicDataSources;

public abstract class DynamicTestDataRowSource(ArgsCode argsCode)
: DynamicDataSourceBase(argsCode)
{
    #region Methods
    #region OptionalToTestDataRow
    /// <summary>
    /// Executes the provided test data function with an optional temporary ArgsCode override.
    /// </summary>
    /// <param name="testDataToTestDataRow">A function that generates test data arguments.</param>
    /// <param name="argsCode">An optional ArgsCode to temporarily use during the execution of <paramref name="testDataToTestDataRow"/>.</param>
    /// <returns>The array of arguments generated by <paramref name="testDataToTestDataRow"/>.</returns>
    /// <remarks>
    /// If <paramref name="argsCode"/> is provided, it will be used during the execution of <paramref name="testDataToTestDataRow"/>
    /// and then automatically restored to the previous value afterward.
    /// </remarks>
    protected ITestDataRow OptionalToTestDataRow(Func<ITestDataRow> testDataToTestDataRow, ArgsCode? argsCode)
    {
        ArgumentNullException.ThrowIfNull(testDataToTestDataRow, nameof(testDataToTestDataRow));
        return WithOptionalArgsCode(this, testDataToTestDataRow, argsCode);
    }
    #endregion

    #region TestDataToTestDataRow
    /// <summary>
    /// Converts test data to a test data row.
    /// </summary>
    /// <typeparam name="T1">The type of the first argument.</typeparam>
    /// <param name="definition">The definition of the test data.</param>
    /// <param name="expected">The expected result of the test.</param>
    /// <param name="arg1">The first argument.</param>
    /// <returns>An array of arguments.</returns>
    protected TestDataRow<TestData<T1>> TestDataToTestDataRow<T1>(
        string definition,
        string expected,
        T1? arg1)
    => new TestData<T1>(
        definition,
        expected,
        arg1)
        .ToTestDataRow(ArgsCode);

    /// <inheritdoc cref="TestDataToTestDataRow{T1}" />
    /// <typeparam name="T2">The type of the second argument.</typeparam>
    /// <param name="arg2">The second argument.</param>
    /// <returns>An array of arguments.</returns>
    protected TestDataRow<TestData<T1, T2>> TestDataToTestDataRow<T1, T2>(
        string definition,
        string expected,
        T1? arg1, T2? arg2)
    => new TestData<T1, T2>(
        definition,
        expected,
        arg1, arg2)
        .ToTestDataRow(ArgsCode);

    /// <inheritdoc cref="TestDataToTestDataRow{T1, T2}" />
    /// <typeparam name="T3">The type of the third argument.</typeparam>
    /// <param name="arg3">The third argument.</param>
    /// <returns>An array of arguments.</returns>
    protected TestDataRow<TestData<T1, T2, T3>> TestDataToTestDataRow<T1, T2, T3>(
        string definition,
        string expected,
        T1? arg1, T2? arg2, T3? arg3)
    => new TestData<T1, T2, T3>(
        definition,
        expected,
        arg1, arg2, arg3)
        .ToTestDataRow(ArgsCode);

    /// <inheritdoc cref="TestDataToTestDataRow{T1, T2, T3}" />
    /// <typeparam name="T4">The type of the fourth argument.</typeparam>
    /// <param name="arg4">The fourth argument.</param>
    /// <returns>An array of arguments.</returns>
    protected TestDataRow<TestData<T1, T2, T3, T4>> TestDataToTestDataRow<T1, T2, T3, T4>(
        string definition,
        string expected,
        T1? arg1, T2? arg2, T3? arg3, T4? arg4)
    => new TestData<T1, T2, T3, T4>(
        definition,
        expected,
        arg1, arg2, arg3, arg4)
        .ToTestDataRow(ArgsCode);

    /// <inheritdoc cref="TestDataToTestDataRow{T1, T2, T3, T4}" />
    /// <typeparam name="T5">The type of the fifth argument.</typeparam>
    /// <param name="arg5">The fifth argument.</param>
    /// <returns>An array of arguments.</returns>
    protected TestDataRow<TestData<T1, T2, T3, T4, T5>> TestDataToTestDataRow<T1, T2, T3, T4, T5>(
        string definition,
        string expected,
        T1? arg1, T2? arg2, T3? arg3, T4? arg4, T5? arg5)
    => new TestData<T1, T2, T3, T4, T5>(
        definition,
        expected,
        arg1, arg2, arg3, arg4, arg5)
        .ToTestDataRow(ArgsCode);

    /// <inheritdoc cref="TestDataToTestDataRow{T1, T2, T3, T4, T5}" />
    /// <typeparam name="T6">The type of the sixth argument.</typeparam>
    /// <param name="arg6">The sixth argument.</param>
    /// <returns>An array of arguments.</returns>
    protected TestDataRow<TestData<T1, T2, T3, T4, T5, T6>> TestDataToTestDataRow<T1, T2, T3, T4, T5, T6>(
        string definition,
        string expected,
        T1? arg1, T2? arg2, T3? arg3, T4? arg4, T5? arg5, T6? arg6)
    => new TestData<T1, T2, T3, T4, T5, T6>(
        definition,
        expected,
        arg1, arg2, arg3, arg4, arg5, arg6)
        .ToTestDataRow(ArgsCode);

    /// <inheritdoc cref="TestDataToTestDataRow{T1, T2, T3, T4, T5, T6}" />
    /// <typeparam name="T7">The type of the seventh argument.</typeparam>
    /// <param name="arg7">The seventh argument.</param>
    /// <returns>An array of arguments.</returns>
    protected TestDataRow<TestData<T1, T2, T3, T4, T5, T6, T7>> TestDataToTestDataRow<T1, T2, T3, T4, T5, T6, T7>(
        string definition,
        string expected,
        T1? arg1, T2? arg2, T3? arg3, T4? arg4, T5? arg5, T6? arg6, T7? arg7)
    => new TestData<T1, T2, T3, T4, T5, T6, T7>(
        definition,
        expected,
        arg1, arg2, arg3, arg4, arg5, arg6, arg7)
        .ToTestDataRow(ArgsCode);

    /// <inheritdoc cref="TestDataToTestDataRow{T1, T2, T3, T4, T5, T6, T7}" />
    /// <typeparam name="T8">The type of the eighth argument.</typeparam>
    /// <param name="arg8">The eighth argument.</param>
    /// <returns>An array of arguments.</returns>
    protected TestDataRow<TestData<T1, T2, T3, T4, T5, T6, T7, T8>> TestDataToTestDataRow<T1, T2, T3, T4, T5, T6, T7, T8>(
        string definition,
        string expected,
        T1? arg1, T2? arg2, T3? arg3, T4? arg4, T5? arg5, T6? arg6, T7? arg7, T8? arg8)
    => new TestData<T1, T2, T3, T4, T5, T6, T7, T8>(
        definition,
        expected,
        arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8)
        .ToTestDataRow(ArgsCode);

    /// <inheritdoc cref="TestDataToTestDataRow{T1, T2, T3, T4, T5, T6, T7, T8}" />
    /// <typeparam name="T9">The type of the ninth argument.</typeparam>
    /// <param name="arg9">The ninth argument.</param>
    /// <returns>An array of arguments.</returns>
    protected TestDataRow<TestData<T1, T2, T3, T4, T5, T6, T7, T8, T9>> TestDataToTestDataRow<T1, T2, T3, T4, T5, T6, T7, T8, T9>(
        string definition,
        string expected,
        T1? arg1, T2? arg2, T3? arg3, T4? arg4, T5? arg5, T6? arg6, T7? arg7, T8? arg8, T9? arg9)
    => new TestData<T1, T2, T3, T4, T5, T6, T7, T8, T9>(
        definition,
        expected,
        arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9)
        .ToTestDataRow(ArgsCode);
    #endregion

    #region TestDataReturnsToTestDataRow
    /// <summary>
    /// Converts test data to a test data row that expects a struct to assert.
    /// </summary>
    /// <typeparam name="TStruct">The type of the expected result, which must be a not null <see cref="ValueType"/> object.</typeparam>
    /// <typeparam name="T1">The type of the first argument.</typeparam>
    /// <param name="definition">The definition of the test data.</param>
    /// <param name="expected">The expected struct of the test.</param>
    /// <param name="arg1">The first argument.</param>
    /// <exception cref="InvalidOperationException">Thrown when the <see cref="ArgsCode"/> property has an invalid value.</exception>
    /// <returns>
    /// An array of arguments to be used in a test that expects an not nullable
    /// <see cref="ValueType" /> object of type <typeparamref name="TStruct"/>.
    /// </returns>
    protected TestDataRow<TestDataReturns<TStruct, T1>> TestDataReturnsToTestDataRow<TStruct, T1>(
        string definition,
        TStruct expected,
        T1? arg1)
    where TStruct : struct
    => new TestDataReturns<TStruct, T1>(
        definition,
        expected,
        arg1)
        .ToTestDataRow(ArgsCode);

    /// <inheritdoc cref="TestDataReturnsToTestDataRow{TStruct, T1}" />
    /// <typeparam name="T2">The type of the second argument.</typeparam>
    /// <param name="arg2">The second argument.</param>
    protected TestDataRow<TestDataReturns<TStruct, T1, T2>> TestDataReturnsToTestDataRow<TStruct, T1, T2>(
        string definition,
        TStruct expected,
        T1? arg1, T2? arg2)
    where TStruct : struct
    => new TestDataReturns<TStruct, T1, T2>(
        definition,
        expected,
        arg1, arg2)
        .ToTestDataRow(ArgsCode);

    /// <inheritdoc cref="TestDataReturnsToTestDataRow{TStruct, T1, T2}" />
    /// <typeparam name="T3">The type of the third argument.</typeparam>
    /// <param name="arg3">The third argument.</param>
    protected TestDataRow<TestDataReturns<TStruct, T1, T2, T3>> TestDataReturnsToTestDataRow<TStruct, T1, T2, T3>(
        string definition,
        TStruct expected,
        T1? arg1, T2? arg2, T3? arg3)
    where TStruct : struct
    => new TestDataReturns<TStruct, T1, T2, T3>(
        definition,
        expected,
        arg1, arg2, arg3)
        .ToTestDataRow(ArgsCode);

    /// <inheritdoc cref="TestDataReturnsToTestDataRow{TStruct, T1, T2, T3}" />
    /// <typeparam name="T4">The type of the fourth argument.</typeparam>
    /// <param name="arg4">The fourth argument.</param>
    /// <returns>An array of arguments.</returns>
    protected TestDataRow<TestDataReturns<TStruct, T1, T2, T3, T4>> TestDataReturnsToTestDataRow<TStruct, T1, T2, T3, T4>(
        string definition,
        TStruct expected,
        T1? arg1, T2? arg2, T3? arg3, T4? arg4)
    where TStruct : struct
    => new TestDataReturns<TStruct, T1, T2, T3, T4>(
        definition,
        expected,
        arg1, arg2, arg3, arg4)
        .ToTestDataRow(ArgsCode);

    /// <inheritdoc cref="TestDataReturnsToTestDataRow{TStruct, T1, T2, T3, T4}" />
    /// <typeparam name="T5">The type of the fifth argument.</typeparam>
    /// <param name="arg5">The fifth argument.</param>
    protected TestDataRow<TestDataReturns<TStruct, T1, T2, T3, T4, T5>> TestDataReturnsToTestDataRow<TStruct, T1, T2, T3, T4, T5>(
        string definition,
        TStruct expected,
        T1? arg1, T2? arg2, T3? arg3, T4? arg4, T5? arg5)
    where TStruct : struct
    => new TestDataReturns<TStruct, T1, T2, T3, T4, T5>(
        definition,
        expected,
        arg1, arg2, arg3, arg4, arg5)
        .ToTestDataRow(ArgsCode);

    /// <inheritdoc cref="TestDataReturnsToTestDataRow{TStruct, T1, T2, T3, T4, T5}" />
    /// <typeparam name="T6">The type of the sixth argument.</typeparam>
    /// <param name="arg6">The sixth argument.</param>
    protected TestDataRow<TestDataReturns<TStruct, T1, T2, T3, T4, T5, T6>> TestDataReturnsToTestDataRow<TStruct, T1, T2, T3, T4, T5, T6>(
        string definition,
        TStruct expected,
        T1? arg1, T2? arg2, T3? arg3, T4? arg4, T5? arg5, T6? args6)
    where TStruct : struct
    => new TestDataReturns<TStruct, T1, T2, T3, T4, T5, T6>(
        definition,
        expected,
        arg1, arg2, arg3, arg4, arg5, args6)
        .ToTestDataRow(ArgsCode);

    /// <inheritdoc cref="TestDataReturnsToTestDataRow{TStruct, T1, T2, T3, T4, T5, T6}" />
    /// <typeparam name="T7">The type of the seventh argument.</typeparam>
    /// <param name="arg7">The seventh argument.</param>
    protected TestDataRow<TestDataReturns<TStruct, T1, T2, T3, T4, T5, T6, T7>> TestDataReturnsToTestDataRow<TStruct, T1, T2, T3, T4, T5, T6, T7>(
        string definition,
        TStruct expected,
        T1? arg1, T2? arg2, T3? arg3, T4? arg4, T5? arg5, T6? arg6, T7? arg7)
    where TStruct : struct
    => new TestDataReturns<TStruct, T1, T2, T3, T4, T5, T6, T7>(
        definition,
        expected,
        arg1, arg2, arg3, arg4, arg5, arg6, arg7)
        .ToTestDataRow(ArgsCode);

    /// <inheritdoc cref="TestDataReturnsToTestDataRow{TStruct, T1, T2, T3, T4, T5, T6, T7}" />
    /// <typeparam name="T8">The type of the eighth argument.</typeparam>
    /// <param name="arg8">The eighth argument.</param>
    protected TestDataRow<TestDataReturns<TStruct, T1, T2, T3, T4, T5, T6, T7, T8>> TestDataReturnsToTestDataRow<TStruct, T1, T2, T3, T4, T5, T6, T7, T8>(
        string definition,
        TStruct expected,
        T1? arg1, T2? arg2, T3? arg3, T4? arg4, T5? arg5, T6? arg6, T7? arg7, T8? arg8)
    where TStruct : struct
    => new TestDataReturns<TStruct, T1, T2, T3, T4, T5, T6, T7, T8>(
        definition,
        expected,
        arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8)
        .ToTestDataRow(ArgsCode);

    /// <inheritdoc cref="TestDataReturnsToTestDataRow{TStruct, T1, T2, T3, T4, T5, T6, T7, t8}" />
    /// <typeparam name="T9">The type of the ninth argument.</typeparam>
    /// <param name="arg9">The ninth argument.</param>
    protected TestDataRow<TestDataReturns<TStruct, T1, T2, T3, T4, T5, T6, T7, T8, T9>> TestDataReturnsToTestDataRow<TStruct, T1, T2, T3, T4, T5, T6, T7, T8, T9>(
        string definition,
        TStruct expected,
        T1? arg1, T2? arg2, T3? arg3, T4? arg4, T5? arg5, T6? arg6, T7? arg7, T8? arg8, T9? arg9)
    where TStruct : struct
    => new TestDataReturns<TStruct, T1, T2, T3, T4, T5, T6, T7, T8, T9>(
        definition,
        expected,
        arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9)
        .ToTestDataRow(ArgsCode);
    #endregion

    #region TestDataThrowsToTestDataRow
    /// <summary>
    /// Converts test data to a test data row that throws an exception.
    /// </summary>
    /// <typeparam name="TException">The type of the exception that is expected to be thrown.</typeparam>
    /// <typeparam name="T1">The type of the first argument.</typeparam>
    /// <param name="definition">The definition of the test data.</param>
    /// <param name="expected">The expected exception of the test data.</param>
    /// <param name="arg1">The first argument.</param>
    /// <exception cref="InvalidOperationException">Thrown when the <see cref="ArgsCode"/> property has an invalid value.</exception>
    /// <returns>
    /// An array of arguments to be used in a test that expects
    /// an exception of type <typeparamref name="TException"/>.
    /// </returns>
    protected TestDataRow<TestDataThrows<TException, T1>> TestDataThrowsToTestDataRow<TException, T1>(
        string definition,
        TException expected,
        T1? arg1)
    where TException : Exception
    => new TestDataThrows<TException, T1>(
        definition,
        expected,
        arg1)
        .ToTestDataRow(ArgsCode);

    /// <inheritdoc cref="TestDataThrowsToTestDataRow{TException, T1}" />
    /// <typeparam name="T2">The type of the second argument.</typeparam>
    /// <param name="arg2">The second argument.</param>
    protected TestDataRow<TestDataThrows<TException, T1, T2>> TestDataThrowsToTestDataRow<TException, T1, T2>(
        string definition,
        TException expected,
        T1? arg1, T2? arg2)
    where TException : Exception
    => new TestDataThrows<TException, T1, T2>(
        definition,
        expected,
        arg1, arg2)
        .ToTestDataRow(ArgsCode);

    /// <inheritdoc cref="TestDataThrowsToTestDataRow{TException, T1, T2}" />
    /// <typeparam name="T3">The type of the third argument.</typeparam>
    /// <param name="arg3">The third argument.</param>
    protected TestDataRow<TestDataThrows<TException, T1, T2, T3>> TestDataThrowsToTestDataRow<TException, T1, T2, T3>(
        string definition,
        TException expected,
        T1? arg1, T2? arg2, T3? arg3)
    where TException : Exception
    => new TestDataThrows<TException, T1, T2, T3>(
        definition,
        expected,
        arg1, arg2, arg3)
        .ToTestDataRow(ArgsCode);

    /// <inheritdoc cref="TestDataThrowsToTestDataRow{TException, T1, T2, T3}" />
    /// <typeparam name="T4">The type of the fourth argument.</typeparam>
    /// <param name="arg4">The fourth argument.</param>
    protected TestDataRow<TestDataThrows<TException, T1, T2, T3, T4>> TestDataThrowsToTestDataRow<TException, T1, T2, T3, T4>(
        string definition,
        TException expected,
        T1? arg1, T2? arg2, T3? arg3, T4? arg4)
    where TException : Exception
    => new TestDataThrows<TException, T1, T2, T3, T4>(
        definition,
        expected,
        arg1, arg2, arg3, arg4)
        .ToTestDataRow(ArgsCode);

    /// <inheritdoc cref="TestDataThrowsToTestDataRow{TException, T1, T2, T3, T4}" />
    /// <typeparam name="T5">The type of the fifth argument.</typeparam>
    /// <param name="arg5">The fifth argument.</param>
    protected TestDataRow<TestDataThrows<TException, T1, T2, T3, T4, T5>> TestDataThrowsToTestDataRow<TException, T1, T2, T3, T4, T5>(
        string definition,
        TException expected,
        T1? arg1, T2? arg2, T3? arg3, T4? arg4, T5? arg5)
    where TException : Exception
    => new TestDataThrows<TException, T1, T2, T3, T4, T5>(
        definition,
        expected,
        arg1, arg2, arg3, arg4, arg5)
        .ToTestDataRow(ArgsCode);

    /// <inheritdoc cref="TestDataThrowsToTestDataRow{TException, T1, T2, T3, T4, T5}" />
    /// <typeparam name="T6">The type of the sixth argument.</typeparam>
    /// <param name="arg6">The sixth argument.</param>
    protected TestDataRow<TestDataThrows<TException, T1, T2, T3, T4, T5, T6>> TestDataThrowsToTestDataRow<TException, T1, T2, T3, T4, T5, T6>(
        string definition,
        TException expected,
        T1? arg1, T2? arg2, T3? arg3, T4? arg4, T5? arg5, T6? arg6)
    where TException : Exception
    => new TestDataThrows<TException, T1, T2, T3, T4, T5, T6>(
        definition,
        expected,
        arg1, arg2, arg3, arg4, arg5, arg6)
        .ToTestDataRow(ArgsCode);

    /// <inheritdoc cref="TestDataThrowsToTestDataRow{TException, T1, T2, T3, T4, T5, T6}" />
    /// <typeparam name="T7">The type of the seventh argument.</typeparam>
    /// <param name="arg7">The seventh argument.</param>
    protected TestDataRow<TestDataThrows<TException, T1, T2, T3, T4, T5, T6, T7>> TestDataThrowsToTestDataRow<TException, T1, T2, T3, T4, T5, T6, T7>(
        string definition,
        TException expected,
        T1? arg1, T2? arg2, T3? arg3, T4? arg4, T5? arg5, T6? arg6, T7? arg7)
    where TException : Exception
    => new TestDataThrows<TException, T1, T2, T3, T4, T5, T6, T7>(
        definition,
        expected,
        arg1, arg2, arg3, arg4, arg5, arg6, arg7)
        .ToTestDataRow(ArgsCode);

    /// <inheritdoc cref="TestDataThrowsToTestDataRow{TException, T1, T2, T3, T4, T5, T6, T7}" />
    /// <typeparam name="T8">The type of the eighth argument.</typeparam>
    /// <param name="arg8">The eighth argument.</param>
    protected TestDataRow<TestDataThrows<TException, T1, T2, T3, T4, T5, T6, T7, T8>> TestDataThrowsToTestDataRow<TException, T1, T2, T3, T4, T5, T6, T7, T8>(
        string definition,
        TException expected,
        T1? arg1, T2? arg2, T3? arg3, T4? arg4, T5? arg5, T6? arg6, T7? arg7, T8? arg8)
    where TException : Exception
    => new TestDataThrows<TException, T1, T2, T3, T4, T5, T6, T7, T8>(
        definition,
        expected,
        arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8)
        .ToTestDataRow(ArgsCode);

    /// <inheritdoc cref="TestDataThrowsToTestDataRow{TException, T1, T2, T3, T4, T5, T6, T7, T8}" />
    /// <typeparam name="T9">The type of the ninth argument.</typeparam>
    /// <param name="arg9">The ninth argument.</param>
    protected TestDataRow<TestDataThrows<TException, T1, T2, T3, T4, T5, T6, T7, T8, T9>> TestDataThrowsToTestDataRow<TException, T1, T2, T3, T4, T5, T6, T7, T8, T9>(
        string definition,
        TException expected,
        T1? arg1, T2? arg2, T3? arg3, T4? arg4, T5? arg5, T6? arg6, T7? arg7, T8? arg8, T9? arg9)
    where TException : Exception
    => new TestDataThrows<TException, T1, T2, T3, T4, T5, T6, T7, T8, T9>(
        definition,
        expected,
        arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9)
        .ToTestDataRow(ArgsCode);
    #endregion
    #endregion
}
